### ISSUE TITLE
Error chart

### ISSUE THREAD

**Issue by anonunlock** [leifermendez/report-system#6]
Al hacer clik en la linea con la bandera aparece el siguiente error , intente repararlo pero no pude , quizás es solo problema de mi instalación pero por si a caso lo dejo aca por si alguien sabe como resolverlo.
![image](https://user-images.githubusercontent.com/47359689/83211840-1d464980-a12c-11ea-8732-bfa7daf3e2aa.png)
![image](https://user-images.githubusercontent.com/47359689/83211874-2df6bf80-a12c-11ea-86b4-46e20f14b639.png)

**Comment by leifermendez** [comment]
@anonunlock perfecto lo reviso y te dejo el comentario
